services:
    db:
        image: davidreinon/sqlpinacoteca:v1
        container_name: contenedorPinacoteca
        ports:
            - "3306:3306"
    php:
        image: davidreinon/phppinacoteca:v1
        container_name: contenedorMiAppPinacoteca
        ports:
            - "8080:80"
        depends_on:
            - db
